import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:mashroom/features/auth/screens/auth_wrapper.dart';
import 'core/theme/app_theme.dart';
import 'firebase_options.dart'; // Ensure this is generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Mushroomy',
      theme: AppTheme.lightTheme,
      home: const AuthWrapper(),
    );
  }
}
